language: csharp
    
before_install:
  - git config --global core.autocrlf false && git config --global core.filemode false
  - echo -e ${CI_KEY} > ~/.ssh/ci
  - chmod 400 ~/.ssh/ci
  - ssh-agent bash -c 'ssh-add ~/.ssh/ci; git clone git@bitbucket.org:OmniQuant/server.git'

script:
  - cd server
  - msbuild
