language: csharp
    
before_install:
  - git config --global core.autocrlf false && git config --global core.filemode false
  - echo -e ${CI_KEY} > ~/.ssh/ci
  - ssh -i ~/.ssh/ci -T git@bitbucket.org
  - GIT_SSH_COMMAND="ssh -i ~/.ssh/ci -F /dev/null" git clone https://javagg@bitbucket.org/OmniQuant/server.git
script:
  - cd server
  - msbuild
