os: Visual Studio 2017

environment:
  CI_KEY:
    secure: m66qAr4lPRD9xWXSXkuM3/1ESQaYP0TOEKODMzC7b9nBZu+oQCu0HFmRYvTfqayT1DkwvdhoLuYuH/uGJHt4+vesICn+3P83KKqi0dgFGtqA0ja6yqzOBFJgGoKUpDk3Ja/15n7NzVfOnhHLiQQ4dh8iW/BYwa7nZudNFW5wSQDTMOrA9vezMOeRt7MmVSyP4KDAZag//QOe3nWf3tGF9b6WjW0oImFO2e4UhzPoW1RSt2NypswBgwXVqFV2254Ka0nweMapBNjCpE+0rTFvpHCOqIXFcsay3NWhQD1h782WNKFgXCtdErY2jg5cmuMiHtrlFxb4wEX/Nb/6WeGHE8k1wdoyXlwFV8gJMo5kw/nJnbHaKddSnXe9CluLt0zmr1nnvT+ThJHYzj3od2c5q8QV0NkkttWANYDhYF1Ap9ixiiXU0m8qVXFwuw+Mv7NUmAhfJo5Qo7FeMy6kG6ZBnlyxV6V8zI3VZnZ1/a5U39aKpegup5PI5Mw1jQ9cn58htHNjEMSQCTCpq0q8zN/NXtv27uEpIeIqp5l7YN4Kq3RwNHvKE9NxcEP+xq1GBaCvsBD2dN5eXy7OjBuSj0HT8PVHIqrJv92MDKWcSWHwBMKPSWlfHN5fHcnBByjfz+s47d8ssRZcJcPyq97DG5HtmQHnsJcy8qR7vy2zAFqioBiMm+frE3LSPvpuaj4UYyZdniv/Di9pXYZOR5sIH9egIDFh7Z/KPiTux7Z3c04Ca0u+VZeAYH1aro8q+xpni5bjiK4m7zjUE1c0aL/evPjmAMlaiCwLyVLw0wOXtAqHTqlefNbDFrP5jRZFVNrF+N1pYSdp7o14SlvjOCd4rDDvI2MUnO9runvv5kXUgGk3y4LXiVS9r8aM2B1OsHyTht8NpFFj4XTFoaGV1GpWB1RA5YSjZY+wycKn11Fw4BmS3Pmig/REVfFRHW8p4lcL+rA/JNhdbikTuuLJaDRKuT0C0nPc9AdeIaRCccXN9SS+t8O6RHmy0Jd9Nd5tgajx/dxunbWABuYId3Xw/X9/w8gQjWs1UtoXefeya/DGTMfwxrnEP6+kaYVQO2M5IWAKCK40+4zqbMlLpGY21K8jI2avzQtqMUrQIWx3ttxiZYV/LRPT7XnSQOIpCfZXJiJChQQphis6NhAdCzbo1OtAZVDYdSIM2RGCT8qOFyYi3oG6vW3lmQKczmfvWrmwibnvxLeECaG0y2YZ4iiZxAnJlWA/BVj3nlvTyNT8437cnbeodk2/J35XaVlFCDcwCPafPitBrOmhJqBEWeyLt7ZRxwKAQ+U3aXAIu8iuOiFsyvbPKX8gfVMIntPYNW0/7buY+mR4ajm64Y4jbwXIZEOyPAbjRWvkOm8dC4AkF/Zvw7zeNRcjzpEbSEkxdBwXLumhDH6bi68RFhRALBODwRRyPS4s2MUV+Js3P+QUD+CnD63Q1Bv5UrwHSVDdhatLrab59k7P8XwXpMjQYzX9/6ZY+dMvM1NZvxez6wzmCPGJWbiSLccDHYyQWb4I4pf77v3VkjrGYsyEbyFZgaQBCervL51ys+9nHfXW7qps2FNWEUzM6c8KQGA+0uGf/ZNqGBalkwCCkPLqQpjTS6Z3vLn6H73bAHrseqw9EQRQm3L5YL+LZ001PVAPGEZhqcoXtvm2o1OZ2LgFKW/SEGgKzJcqY8aNM4zY6LIM19ux0RVYlvrX5h5qN/e7+g/5H6xJZgU3tPTkdZ530Pb28Ykc7TiVybh/hHq2ZDilaaS05lguO8j4a+yuzO0yDeBv5A6B5nsAayWayGoDXQFZcO7jcvo1nxNqevc7Ue/CFEhzCdC2B5K5/kwm6deUJFGBaMRNV8QAeQghXIMYn3ALD+ghrm9IbPuMAallVZTBbUfAdFXxawqJcdyMjJWlogMtbPdicWAFVirqoHsxWahlOKzRaCRb3njWJKK0A0nwc2SgvNzIg5DDaxkdEoRJi/eYVhKGvrXbTg+SmDJrLcomADt6zs8ymvnr7AuWk53X7Hu4T6JroroOVlGL2Uwt3A2hdHaAShz57OqxcnLOIn01vU6Glg3MQsGmOQ2i0e3sa3RjNwLiEIfwxbFFXxoDbC5HEHNycsBGRHFNPPFJJg0nhrVEkHXUnTnORIBQw0NTPzmFwvtDRHkF/osucykAvT/pHCSwN+CrXwSxyZya0B/ZH4ErI/u7vw3RI8pIhx1mN3wBV9npx7mUJzORtU1sBV+MvMzgC/MLQv7bjjUsbzVbGDJQRXuuuC4Xadfeuq7/CG6UYYzIWHbUNlS0cyvCla7yYlHKFpSYwlQoeDI4vJVGgVlkb4SptCXTmwLp1MdhGpC/iVTJ6zJN3VI=
  GIT_SSH_COMMAND:
    ssh -i ~/.ssh/ci -o StrictHostKeyChecking=no
    
configuration:
  - Release
  
before_build:
  - git --version
#  - ps: echo "-----BEGIN RSA PRIVATE KEY-----" > $env:USERPROFILE\.ssh\ci
#  - ps: echo $env:CI_KEY >> $env:USERPROFILE\.ssh\ci
  - ps: $env:CI_KEY.Split("`n") > $env:USERPROFILE\.ssh\ci
#  - ps: echo "-----END RSA PRIVATE KEY-----" >> $env:USERPROFILE\.ssh\ci
  - ps: cat $env:USERPROFILE\.ssh\ci
  - git clone git@bitbucket.org:OmniQuant/server.git
  
build_script:
  - cd server
  - msbuild.exe -Configuration "$env:configuration"
  
