os: Visual Studio 2017

environment:
  CI_KEY:
    secure: QgHkN7T9f9eXswLLXMfJM2YT15O52UJC7jH2iAE/jt9xU5wzb3wOgRYvFsPfFuQCGlkPubwGQCjyTmMr6zvHAI3jp9vZG7Iu0iIHhP57gU10NrK70NVrZ4n2uSeyBs+tnJvApTYbBWXBcING4ePS1gEFYE8wY/wZV6HlGb/CNVKrsBFuLuus3s6V2NA4Cf8rvqBof6mUqbDa5IL5a4AcQDGVGiS/BV4ho4rodemSlo9oL+3/QOPH7lE8c/wzWjrZn9H7o1OgavRthP0xFvLzMMSf9PSYJ54PkQ5D4CZhfTGYaEDPZA/ZgVYRkkYrInPGKtjL1XkclmtuRF4GJS2fIi3rEpGtJrfj9V8PFdbgVpzaVl/p56rLUJew3clRuarDF+SSNf/8sTd8qPPjz26/ptG6UArCku4CMokIFVNqUOcsdZSLZ062cBA+vJSXW72zv2cN5ShW/U+hA/M3Ad7MzdI9oQzVSyfEN1qoe3zl1whgv1sodA2XhHKKAwXS1FVxbIF+iRAqP30/LZkS5mkYlDKaMvLpFk2xbOtbqLfF/WRzr5sqjTlb+txHrmEWFCzE3+cCZoimy/9Eywbsw1LuPrW2eFHjZXBgRWylzMVrqFgCPGJS0yT3gSQNAwCZgYPM30TDbDkmn2EzrSNf0+w0+pqlWg4ee80K9+XOhuw3jQcvDfb+27hPPDRT9Vw0AmjQmGvd16yJpxaa2HpdxDI61+ZeMAzw17Scypfb+KnMIHR3JJUKOnuAbvO+WEJ272Ym/ejFryBnYTu6dfokm+S4yqxnSnw+jo9yy7OC9e9zqQDYi3vHktMq+eXo6PP6l3H6ls2WvxQrBA5ut61Ph67FffId6jdAvImQBZ6kQ+JvjIXHlzIN0Lu7lRlIlaN3E4S3Hr6n4+Fhh64C0mONBlxFNZwgqW6aBeIMNoy8yDtT7lx7imQ1F8Esv6uv00Fq7ZT5+SwimpdeIcKsUfr+0GHkf8jibCD7bd2KJBGAx8+NUHPu69g/UtSnUH+W6RvygIW/z91X/AahdqnHD3knVlb3iBLO+r76KO09BYmqcoeswWRbO+AtwSa2qZqJOjlCgTeheSlSKu3mclFPVcndA/IenL7AyqXcu0V7JJraUm9v79FyvU8L+aXwStXpyCZP2QkR4hUAbQ93jx5K7MMEYKrIze+7Tvm89N6SL4ryancxPhyJEnl+o95UczpszfYvaJA89gzrOfjOLDOI3tapxJlhgCw/C1gth/QdIn2YFz2Di/oPGN20QrC3zEFOwbJJcqZnH6vqFc+Fr6RM1Xs8v7BHFTPwz/IKtpVcIgCD7d7NeP9DnZYqdO3/iB+twXtJddE7vMvj8ZAc1Yw5kWj+B0BNB41Twhf5FzbI6sBBDhMmqwdlXUgI1kPwdIPh5Ox38ZtAHgSSayFsh1kUynqTKOyJ0Fl4g8Eg9MeKhb15fy1YjFxo0F3hiBVV6Ys6P8WLTLt9wPi2lW/YrOe71HU1ZYd0OPqAAZf9+pFVGrQrcQ07NqHiOaYocNp3mZ6+gyMoUUSCsEKZumTeYls3clyg2drSzN3z1EpD6r/OHljzmpDDOgPY2x0m5SSyzh3CREuGjDPZ8+z1wFJoKRoJJrQJ25UwejRbQCuxb/1r6UclOLYqt474GY64yqL0gfj4VzhZtyAR0ZyLkp/zuqOy0OtUiWwuHbRDNga81q0j+rpAwdjgJalpG9tMgOTLGx1hFLch5ckNhbJ4iUjRc4kGdjHByuh2x5hlyETfs3w8Y3BGUeILgTE46h7xw6AT64nGmmq1aPcu0Gmz4e49+IZ7lLxUyh/qFq38GQTjzE0ZNmrjRXmVi67hB2cfg6eThy2tpK3NvA6FYIS9ia+uHFWXCZHhEZeluhSW+mx1TSvB7GZhX5pBu+hApo12nJ6qtNiUmu0Z60I+HBFenzcA03NVUZT9wkd7J7PjV5oQTTpVLxeYs5LKqT9Ukhf01SfTbw8y7j6Y/gwp1PGBjO7VKcg0tkIniZCYFmvoQFH3mosJlNEM7xbG/0YR6OH8n38gm0CrqqrpuNnRN3X+z3bgVq/7OgO5Ha6gBVkyhKwIsC72sJL2Hk5s2xOZ4rekXXTl3rqeHTbJqlPPVd3QBuifZ8i3BDFwNhaing==
  GIT_SSH_COMMAND:
    ssh -i ~/.ssh/ci -o StrictHostKeyChecking=no
    
configuration:
  - Release
  
before_build:
  - git --version
  - ps: echo "-----BEGIN RSA PRIVATE KEY-----" > $env:USERPROFILE\.ssh\ci
  - ps: echo $env:CI_KEY >> $env:USERPROFILE\.ssh\ci
  - ps: echo "-----END RSA PRIVATE KEY-----" >> $env:USERPROFILE\.ssh\ci
  - cat $env:USERPROFILE\.ssh\ci
  - git clone git@bitbucket.org:OmniQuant/server.git
  
build_script:
  - cd server
  - msbuild.exe -Configuration "$env:configuration"
  
