os: Visual Studio 2017

configuration:
  - Release
  
before_build:
  - git submodule update --init
  - git clone git@bitbucket.org:OmniQuant/server.git
  
build_script:
  - cd server
  - msbuild.exe -Configuration "$env:configuration"
  
